theme: jekyll-theme-cayman
twitter_username: camwardzala
github_username:  cwardzala

titlecase: true

permalink: /blog/:year/:month/:day/:title.html

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
- CNAME
